server:
  port: 8888
  servlet:
   context-path: /websocket-chat-boot
   session:
     cookie:
       same-site: none
       secure: true
       http-only: true # 是否让浏览器通过js读取cookie

# mysql连接
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/websocket_chat?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver